Repository depromeet/Tiqui-Taca_iOS, pull requests merged in 2022-05, with the labels that each got.

#41 Implement ChatTab
  TiquiTaca_iOS.xcodeproj/project.pbxproj
  TiquiTaca_iOS/Extensions/Color+Extensions.swift
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/colorStar.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/colorStar.imageset/colorStar-1.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/colorStar.imageset/colorStar-2.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/colorStar.imageset/colorStar.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/people.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/people.imageset/people-1.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/people.imageset/people-2.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/people.imageset/people.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/rightArrow.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/rightArrow.imageset/rightArrow-1.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/rightArrow.imageset/rightArrow-2.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/rightArrow.imageset/rightArrow.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/star.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/star.imageset/star-1.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/star.imageset/star-2.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Chat/star.imageset/star.png
  TiquiTaca_iOS/Views/App/AppCore.swift
  TiquiTaca_iOS/Views/Chat/Cell/RoomListCell.swift
  TiquiTaca_iOS/Views/Chat/ChatCore.swift
  TiquiTaca_iOS/Views/Chat/ChatView.swift
  TiquiTaca_iOS/Views/MainTab/MainTabCore.swift
  TiquiTaca_iOS/Views/MainTab/MainTabView.swift
Labels: High, Feature

#50 Temp MsgAndNoti Tab
  TiquiTaca_iOS.xcodeproj/project.pbxproj
  TiquiTaca_iOS/Components/TabViewItem.swift
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Graphic/letter_g.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Graphic/letter_g.imageset/noLetter 1.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Graphic/noti_g.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Graphic/noti_g.imageset/noalarm 1.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/chat.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/chat.imageset/unselected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/chat_active.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/chat_active.imageset/selected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/letter.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/letter.imageset/unselected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/letter_active.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/letter_active.imageset/selected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/map.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/map.imageset/unselected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/map_active.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/map_active.imageset/selected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/mypage.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/mypage.imageset/unselected.png
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/mypage_active.imageset/Contents.json
  TiquiTaca_iOS/Resource/Assets.xcassets/Hakyung/Tabbar/mypage_active.imageset/selected.png
  TiquiTaca_iOS/Views/MainTab/MainTabView.swift
  TiquiTaca_iOS/Views/MsgAndNoti/MsgAndNotiCore.swift
  TiquiTaca_iOS/Views/MsgAndNoti/MsgAndNotiView.swift
Labels: Low

#52 FCM push notification bugfix
  TiquiTaca_iOS.xcodeproj/project.pbxproj
  TiquiTaca_iOS/SupportingFile/Info.plist
  TiquiTaca_iOS/TiquiTaca_iOSDebug.entitlements
  TiquiTaca_iOS/Views/App/AppCore.swift
Labels: Medium, Bug
