Repository depromeet/Tiqui-Taca_iOS, pull requests merged in 2022-04, with the labels that each got.

#8 프로젝트 파일 추가
  TiquiTaca_iOS.xcodeproj/project.pbxproj
  TiquiTaca_iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TiquiTaca_iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TiquiTaca_iOS/Assets.xcassets/AccentColor.colorset/Contents.json
  TiquiTaca_iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  TiquiTaca_iOS/Assets.xcassets/Contents.json
  TiquiTaca_iOS/ContentView.swift
  TiquiTaca_iOS/Preview Content/Preview Assets.xcassets/Contents.json
  TiquiTaca_iOS/TiquiTaca_iOSApp.swift
  TiquiTaca_iOSTests/TiquiTaca_iOSTests.swift
  TiquiTaca_iOSUITests/TiquiTaca_iOSUITests.swift
  TiquiTaca_iOSUITests/TiquiTaca_iOSUITestsLaunchTests.swift
Labels: High, Feature

#15 README Update
  README.md
Labels: Feature

#17 Add Tech Stack at README.md
  README.md
  TiquiTaca_iOS.xcodeproj/project.pbxproj
Labels: Low

#21 GithubActions: Add SwiftLint Workflow
  .github/workflows/swiftlint.yml
  .swiftlint.yml
  TiquiTaca-iOS-Info.plist
  TiquiTaca_iOS.xcodeproj/project.pbxproj
  TiquiTaca_iOS/ContentView.swift
  TiquiTaca_iOS/TiquiTaca_iOSApp.swift
  TiquiTaca_iOSTests/TiquiTaca_iOSTests.swift
Labels: Feature

#22 GithubActions: deploy on TestFlight
  .github/workflows/deploy_on_TestFlight_master.yml
Labels: Bug

#28 Feature/Add Splash, Onboarding, MainTabView
  TiquiTaca_iOS.xcodeproj/project.pbxproj
  TiquiTaca_iOS/Components/PageControl.swift
  TiquiTaca_iOS/Extensions/View+Extensions.swift
  TiquiTaca_iOS/Resource/LaunchScreen.storyboard
  TiquiTaca_iOS/TiquiTaca_iOSApp.swift
  TiquiTaca_iOS/Views/ChatView/ChatCore.swift
  TiquiTaca_iOS/Views/ChatView/ChatView.swift
  TiquiTaca_iOS/Views/MainTabView/MainTabCore.swift
  TiquiTaca_iOS/Views/MainTabView/MainTabView.swift
  TiquiTaca_iOS/Views/MapView/MapCore.swift
  TiquiTaca_iOS/Views/MapView/MapView.swift
  TiquiTaca_iOS/Views/MsgAndNotiView/MsgAndNotiCore.swift
  TiquiTaca_iOS/Views/MsgAndNotiView/MsgAndNotiView.swift
  TiquiTaca_iOS/Views/MyPageView/MyPageCore.swift
  TiquiTaca_iOS/Views/MyPageView/MyPageView.swift
  TiquiTaca_iOS/Views/OnboardingView/OnboardingCore.swift
  TiquiTaca_iOS/Views/OnboardingView/OnboardingView.swift
  TiquiTaca_iOS/Views/SplashView/SplashView.swift
Labels: Feature
